//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class prlicula
    {
        public int id { get; set; }
        public string nombreorg { get; set; }
        public string nombrees { get; set; }
        public string nombreing { get; set; }
        public string sinopsis { get; set; }
        public string genero { get; set; }
        public string genero2 { get; set; }
        public string genero3 { get; set; }
        public string año { get; set; }
        public string linkimg { get; set; }
        public string linkvid { get; set; }
    }
}
